### Section 2.1 (Exploring categorical data) {-}

\setstretch{1}

**Videos**  

* 2.1
* MosaicPlots

\setstretch{1.25}

#### Vocabulary {-}

Frequency table:
\rgs

Relative frequency table:
\rgs

Contingency or two-way table:
\rgs

Unconditional proportion:
\rgs

Conditional proportion:
\rgs

\rgi Row proportions:
\rgs

\rgi Column proportions:
\rgs

Statistic:
\rgs

\rgi Sample proportion:
\rgs

\rgi \rgi Notation:
\rgs

Parameter:
\rgs

\rgi Population proportion:
\rgs

\rgi \rgi Notation:
\rgs

Bar plot:
\rgs

Segmented bar plot:
\rgs

Simpson’s Paradox:
\rgs


#### Notes {-}

In a contingency table, which variable (explanatory or response) generally will make the columns of the table?  Which variable will make the rows of the table?
\rgs

In a segmented bar plot, the bars represent the levels of which variable?  The segments represent the levels of which variable?
\rgs

What type of plot(s) are appropriate to display a single categorical variable?
\rgs


What type of plot(s) are appropriate to display two categorical variables?
\rgs


What is the difference between a standardized segmented bar plot and a mosaic plot?
\rgs

True or false: Pie charts are generally highly recommended ways to graphically display categorical data.

True or false: Two categorical variables are associated if the conditional proportions of a particular outcome (typically of the response variable) differ across levels of the other variable (typically the explanatory variable).

True or false: When a segmented bar plot has segments that sum to 1 (or 100%), the segment heights correspond to the proportions conditioned on the **segment**.

#### Review of Simpson’s Paradox {-}

Based on the segmented bar plot in Figure 2.6, which race of defendant was more likely to have the death penalty invoked?
\rgs

Based on the segmented bar plot in Figure 2.7 and Table 2.9, which race of defendant was more likely to have the death penalty invoked when the victim was Caucasian?
\rgs

Based on the segmented bar plot in Figure 2.7 and Table 2.9, which race of defendant was more likely to have the death penalty invoked when the victim was African American?
\rgs

The direction of the relationship between the ______________
and ______________ variables is **reversed** when accounting for
a ______________ variable.


#### Data Visualization Summary

Fill in the following table to help associate type of plot for each of several scenarios.

\begin{center}
\begin{tabular}{|l|p{3in}|} \hline
 & Appropriate plot(s) \\ \hline
One categorical variable & \\
(categorical response, no explanatory) & \\ \hline
One quantitative variable  & \\
(quantitative response, no explanatory) & \\ \hline
Two categorical variables  & \\
(categorical response, categorical explanatory) & \\ \hline
One of each  & \\
(quantitative response, categorical explanatory) & \\ \hline
Two quantitative variables  & \\
(quantitative response, quantitative explanatory) & \\ \hline
\end{tabular}
\end{center}

Decision tree for determining an appropriate plot  given a number of variables and their types from Chapter 2 review:

```{r decision-tree-plots, fig.fullwidth=TRUE}
pal <- c("#000000", brewer.pal(8, 'Dark2'))

data <- data.frame(
  level1 = "Resp",
  level2 = c(rep("Quan0",7), rep("Cat0",5)),
  level3 = c(rep(c("None","Cat","Quant"),c(1,2,4)),
             rep(c("None2","Cat2","Quant2"),c(2,2,1))),
  level4 = paste0("plot_", letters[1:12])
)

# transform to edge list
edges_level1_2 = data %>% select(level1, level2) %>% unique %>% rename(from=level1, to=level2)
edges_level2_3 = data %>% select(level2, level3) %>% unique %>% rename(from=level2, to=level3)
edges_level3_4 = data %>% select(level3, level4) %>% unique %>% rename(from=level3, to=level4)
edge_list=rbind(edges_level1_2, edges_level2_3, edges_level3_4)

# decision tree
mygraph <- graph_from_data_frame( edge_list )
ggraph(mygraph, layout = 'dendrogram', circular = FALSE) + 
  geom_edge_diagonal(arrow = arrow(length = unit(3, 'mm')), 
                   end_cap = circle(2, 'mm')) +
  geom_node_point(color="#69b3a2", size=1) +
  geom_node_label(
    aes(   label=c("Response variable",
                   "Quantitative", "Categorical",
                  rep(c("Quantitative","Categorical","None"),2),
                  "Scatterplot",
                  "Stacked histogram", 
                  "Side-by-side box plots", "Box plot",
                  "Density plot", "Histogram",
                  "Dot plot", "Side-by-side box plots",
                  "Smoothed scatterplot", "Segmented bar plot", 
                  "Mosaic plot", "Bar plot")),
    label.padding = unit(0.3, "lines"),
    color = pal[c(1:9,4,5,5,6,6,6,6,7,7,8,8,9)],
    size = c(4,rep(3.5,20)),
    fontface = c("bold",rep("plain",20)),
    nudge_x = c(rep(.5,9),rep(0,12)),
    nudge_y = c(rep(0,9),rep(.7,12))
                # c(.6,.8,.9,.47,.6,.55,.45,.9,.9,.9, .6,.5))
    ) +
  theme(plot.margin = margin(t=20, r=20, b=20, l=20, unit="pt")) +
  coord_flip() +
  scale_y_reverse(expand = c(.2,.2)) +
  scale_x_discrete() +
  annotate("text",  x = 6.1, y = 1, label = "Explanatory variable",
           fontface = "bold", size = 4)
```


