---
title: "Week 1 Reading Guide"
output: html_document
---

## Chapter 1: Data, Types of Variables & Study Design

### Section 1.1 

Summary statistic:

</br>

### Section 1.2.1: Observations, Variables & Data Matrices

Case / Observational unit:

</br>

Variable:

</br>

Data:

</br>

Data frame:

</br>

Tidy data:

</br>

### Section 1.2.2: Types of Variables

Numerical / Quantitative variable:

</br>

Discrete variable:

</br>

Examples of a discrete variable using the `county` data: 

</br>

Continuous variable:

</br>

Examples of a continuous variable using the `county` data: 

</br>

Example of a variable recorded as a number which **is not** a numerical
variable: 

</br>

Categorical / Qualitative variable:

</br>

Levels of a categorical variable:

</br>

Ordinal variable:

</br>

Example of an ordinal variable using the `county` data:

</br>

Nominal variable:

</br>

Example of a nominal variables using the `county` data:

</br>

**Note: Ordinal and nominal variables will be treated the same in this course.
I recommend taking more statistics courses in the future to learn better
methods of analysis for ordinal variables!**

### Section 1.2.3: Relationships Between Variables

Association / Dependent variables:

</br>

Independent variables:

</br>

### Section 1.2.4: Explanatory & Response Variables

Explanatory variable:

</br>

Response variable:

</br>

### Section 1.2.5: Observational Studies & Experiments

Experiment:

</br>

Randomized Experiment:

</br> 

Placebo:

</br>

Observational study:

</br>

Cohort:

</br>

#### Notes

In a data frame, rows correspond to: ___________________ 

In a data frame, columns correspond to: __________________.

</br>

True or False: A pair of variables can be both associated AND independent.

</br>

True or False: Given a pair of variables, one will always be the explanatory
variable and one the response variable.  

</br>

True or False: If a study does have an explanatory and a response variable,
that means changes in the explanatory variable must **cause** changes in the
response variable. 

</br>

True or False: Observational studies can show a naturally occurring association
between variables.  

</br>

---

## Chapter 2: Sampling & Experimental Design

Statistic:

</br>

Parameter:

</br>

### Section 2.1.1: Populations & Samples

(Target) Population:

</br>

Census:

</br>

Sample:

</br>

### Section 2.1.2: Parameters & Statistics

Statistic:

</br>

Parameter:

</br>

### Section 2.1.3: Anecdotal Evidence

Anecdotal evidence

</br>

### Section 2.1.4: Sampling from a Population

Bias:

</br>

Simple Random Sample:

</br>

Representative:

</br>

Non-response bias:

</br>

Response bias:

</br>

Convenience sample:

</br>

#### Notes

* Someone must first be _chosen_ to be in a study and refuse to participate in
order to have **non-response bias**.

* There must be a valid reason for someone to lie or be untruthful to justify
saying **response bias** is present.  Yes, anyone could lie at any time to any
question.  Response bias is when those lies are predictable and systematic based
on outside influences.

</br>

True or False: Convenience sampling tends to result in non-response bias.

</br>

True or False: Volunteer sampling tends to result in response bias.

</br>

### Section 2.1.5: Four Sampling Methods

Simple Random Sampling:

</br>

Stratified Sampling:

</br>

Strata:

</br>

Cluster Sample:

</br>

Clusters:

</br>

Multistage Sample:

</br>

#### Notes 

Ideally, how should we sample cases from our target population? Using what
sampling method? 

</br>

True or False: Random sampling helps to resolve selection bias, but has no 
impact on non-response or response bias.

</br>

### Section 2.2.1: Principles of Experimental Design

Controlling:

</br>

Control:

</br>

Randomization:

</br>

Confounding Variable:

</br>

Replication:

</br>

Replicate:

</br>

Blocking:

</br>

Blocks:

</br>

### Section 2.2.2: Reducing Bias in Human Experiments

Treatment Group:

</br>

Control Group:

</br>

Blind:

</br>

Placebo:

</br>

Placebo effect:

</br>

Double Blind:

</br>

### Section 2.3: Observational Studies 

Observational Data:

</br>

Prospective Study:

</br>

Retrospective Study:

</br>

#### Notes

What are the four principles of a well-designed randomized experiment?  
</br>
</br>
</br>

Fill in the appropriate scope of inference for each study design.
\begin{center}
\begin{tabular}{|p{2in}|p{2in}|p{2in}|}
\hline
 & \multicolumn{2}{|c|}{\textbf{Study Type}} \\ \hline
 \textbf{Selection of Cases} & Randomized experiment & Observational study \\ \hline
 Random sample && \\ 
 (and no other sampling bias) & & \\ 
  & & \\
   & & \\ \hline
   Non-random sample && \\ 
   (or other sampling bias) & & \\ 
  & & \\
   & & \\ \hline
\end{tabular}
\end{center}

</br>

True or False: Observational studies can show an association between two
variables, but cannot determine a causal relationship.

</br>

True or False: In order for an experiment to be valid, a placebo must be used.

</br>

True or False: If random sampling of the target population is used, and no other
types of bias are suspected, results from the sample can be generalized to the
entire target population.

</br>

True or False: If random sampling of the target population is used, and no other
types of bias are suspected, results from the sample can be inferred as a causal
relationship between the explanatory and response variables.

</br>