## Week 14 Lab: Efficacy of the COVID Vaccination

\setstretch{1}

### Learning outcomes

* Recognize and simulate probabilities as long-run frequencies.

* Use two-way tables to calculate conditional probabilities.

* Interpret the value of relative risk in terms of a percent increase or decrease.

* Evaluate the association between two categorical variables using relative risk.

### Efficacy of the COVID vaccination

In November 2021, it was estimated that 59.1\% of all US adults ($\ge$ 18 years old) were fully vaccinated against COVID-19 [@covidvaccinetracker].   While vaccination is not 100\% effective at protection against COVID-19, there are also other benefits to the vaccine.  What impact does vaccination have on hospitalization rates for COVID?  The following hypothetical two-way table was created based on CDC data on adult hospitalizations for COVID in the US [@cdchospitalization] in the same time period.  

Let $A$ = the event the US adult is vaccinated, and $B$ = the event the US adult is hospitalized with COVID. 

|                             |  Vaccinated | Not Vaccinated |    Total   |
|-----------------------------|-------------|----------------|------------|
| Hospitalized with COVID     |     2.309   |      27.7302   |    30.0392 |
| Not hospitalized with COVID | 59,097.6951 |   40,872.2698  |   99,96949 |
| Total                       |   59,100    |      40,900    |    100,000 |


1.  What is the probability that a US adult is both hospitalized with COVID-19 and vaccinated? Use proper probability notation.

\vspace{0.8in}

2.  **What is the probability that a US adult hospitalized with a COVID infection is vaccinated?  Use proper probability notation.**

\vspace{0.8in}

3.  What is the probability that a US adult is hospitalized with a COVID infection in November 2021?  Use proper probability notation.

\vspace{0.8in}

\newpage

4.  **Give the probability notation for the calculation $\frac{27.7302}{30.0392} = 0.923$.  Write out what this probability measures in words.**

\vspace{0.8in}

5.  What is the probability that a vaccinated US adult is hospitalized with COVID?

\vspace{0.5in}

6.  What is the probability that a un-vaccinated US adult is hospitalized with COVID?

\vspace{0.5in}

7.  **Calculate the relative risk for hospitalization with COVID in November 2021 for US adults fully vaccinated compared US adults not vaccinated.**

\vspace{0.5in}

8.  Calculate the percent increase (or decrease) in hospitalization rate for US adults fully vaccinated compared to US adults not vaccinated.

\vspace{0.5in}

9. **Interpret the relative risk as a percent increase/decrease in context of the problem.**

\vspace{0.5in}

10. **Does it appear that there is an association with the risk of hospitalization due to COVID-19 and vaccination status? Explain.**

\vspace{0.5in}

11.  **Explain why a hypothesis test would not be appropriate in this case.**

\newpage