---
title: "Your Title Goes Here! Make it fun!"
author: "Your Name Here!"
output: html_document
---

```{r setup, include = FALSE}
# This is code to make your report format look nice! 
# Please don't modify these options! 
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.align = "center")

# The code to load in the necessary packages goes here!
# You will need: tidyverse, mosaic, and moderndive


```

```{r data}
# This is where you will load in your data! 
# I suggest copying and pasting code from a prior lab. 
# You will need to change: 
# 1. the name of the dataset (you get to choose the name)
# 2. directions for how to get to the data


```

## Data Description
<!-- In this section you are to describe your dataset! -->

<!-- This section has three tasks:
1. Describe the context of your dataset in your own words!
2. Tell me why you picked this dataset
3. Describe the two variables you are interested in. One should be the
explanatory variable and one should be the response.
-->



## Data Visualization
<!-- In this section you create three visualizations of your data -->

### Histogram of <INSERT NAME OF RESPONSE VARIABLE>

```{r histogram-1}
## Code to make your firsthistogram goes here! 
## Don't forget to choose nice binwidths and an axis title!


```
<!-- Here is where you describe what you see in the histogram. Your description must include the following components: center, spread, shape, outliers -->



### Histogram of <INSERT NAME OF EXPLANATORY VARIABLE>

```{r histogram-2}
## Code to make your second histogram goes here! 
## Don't forget to choose nice binwidths and an axis title!


```
<!-- Here is where you describe what you see in the histogram. Your description must include the following components: center, spread, shape, outliers -->



### Scatterplot of <INSERT NAME OF RESPONSE VARIABLE> and <INSERT NAME OF EXPLANATORY VARIABLE>

```{r scatterplot}
## Code to make your scatterplot goes here! 
## Don't forget to choose nice axis labels!


```

<!-- Here is where you describe what you see in the scatterplot. Your description must include the following components: direction, shape, strength, outliers -->

## Linear Relationship Between <INSERT NAME OF RESPONSE VARIABLE> and <INSERT NAME OF EXPLANATORY VARIABLE>

### Model Conditions
<!-- Here is where you describe the four conditions (LINE) for linear regression.  -->
<!-- State what the condition is and if you believe it is / is not violated IN THE CONTEXT OF YOUR DATA! -->


### Coefficient Estimates

```{r lm}
## Code to fit a linear regression

## Code to get coefficient table from linear regression

```

### Inference for the Slope

<!-- Here is where you describe the decision for the hypothesis test for whether the slope is 0.  -->



<!-- Here is where you describe the confidence interval for the true slope. -->


