---
title: "Chapter 18: Inference for Two-Way Tables"
output: html_document
---

## 18.2: Randomization test of independence

__What does the null hypothesis assume about the probability of the seller
disclosing the problem?__

</br>

__Under the null hypothesis does this probability differ based on the question 
that the buyer asked?__

</br>
</br>

__What did the researchers define a "success" in the iPod study?__

</br>

### 18.1.1 -- Expected Counts

__Based on Table 18.1, how was the proportion of $61 / 219$ found? What does 
this proportion represent?__ 

</br>
</br>

__If there had been 85 people in the "Negative assumption" group, what would 
be the expected counts for "Disclose problem" and "Hide problem"?__

</br>
</br>

__What is the general formula for calculating the expected count of a specific
cell in a two-way table?__

</br>
</br>

### 18.1.2 -- The chi-squared statistic

__What is the formula for calculating *one* cell's contribution to the
chi-squared statistic?__

</br>
</br>

### 18.1.3 -- Variability of Statistic

If the null hypothesis was true, we are assuming that the seller would disclose
the problem with the iPod the same proportion of the time, regardless of the 
question that the buyer asked. 

The book doesn't cover this explicitly, but I'd like for you to think about 
how you could use cards to simulate what $X^2$ statistics could have happened if
the null was true. 

__Step 1:__ Write the outcome (disclose / hide) and the question (general /
positive assumption / negative assumption) on a card. 

__How many cards will there be total?__

</br>
</br>

__Step 2:__ Assume the null hypothesis is true and....

__What will be done with the cards?__

</br>
</br>

__Step 3:__ Generate a new sample that could have happened if the null was true
by....

__How will a new sample be made with the cards?__

</br>
</br>

__Step 4:__ Calculate the simulated....

__What statistic will be calculated from the new sample?__

</br>
</br>

### 18.1.4 -- Observed Statistic vs. Null Statistics

__For an observed statistic like what is seen in Figure 18.1, what would be 
the approximate p-value?__

</br>

__What does the p-value you stated above *mean* in the context of the observed
statistic and the null distribution?__

</br>
</br>

---

## 18.2 -- Mathematical Model for Test of Independence

Based on Figure 18.2, complete the following sentence: 

__As the degrees of freedom for a Chi-Squared distribution get larger, the 
shape of the distribution gets less...__

### 18.2.2 -- Variablity of the Chi-Squared Statistic

__What two conditions are required to be checked to use the Chi-Squared
distribution to obtain a p-value?__

</br>
</br>

__Which of these conditions is required *regardless* of the method you use to
find the p-value (simulation-based or theory-based)?__

</br>
</br>

__True or false: The formula for finding the $X^2$ statistic is the same for 
both simulation-based (randomization) and theory-based (mathematical) methods.__




